### PR TITLE
Delete package-lock.json

### PR DESCRIPTION
**Pull request by maximelkin**
#2

### CODE REVIEW

**Comment by maximelkin** [comment]
@kibertoad

**Comment by kibertoad** [comment]
We should remove `npm ci` and caching from https://github.com/knex/knex-utils/blob/master/.circleci/config.yml then.

**Comment by kibertoad** [comment]
` key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}` this also is not going to work anymore.

**Comment by kibertoad** [comment]
so we probably need to replace it with package.json

**Comment by kibertoad** [comment]
@maximelkin How would caching work if there is no checksum for invalidating it? Probably we should drop caching entirely.

**Comment by maximelkin** [comment]
I think its not needed, because npm i can reuse existing node_modules, and cases when dependencies bumped rare enough

**Comment by kibertoad** [comment]
@maximelkin let's remove caching overall then

**Comment by maximelkin** [comment]
ok

**Pull request merged**
